### PR TITLE
recipes-devtools: gcc: remove superseded recipe

### PR DESCRIPTION
**Pull request by angeloc**
openembedded kirkstone moved to gcc 11.4 so this patch is not needed anymore.

### CODE REVIEW

**Comment by ruben-sch** [comment]
+1 for this. Any plans when it will be merged?

**Comment by BernardPuel** [comment]
ST did that patch because There are some version of GCC where "gcc plugins" don't work in Yocto SDK.

ST fixed the version to 11.3 to force to check for each GCC version if it's still necessary (just build the kernel with latest SDK with GCC11.4 and without the patch or have a look to GCC source code). 

If still necessary, ST do not suggest  to remove that patch but to update it to 11.4. Test ongoing and planned delivery in V4.1.2 Release (next one).

**Comment by angelo-zehnder** [comment]
Any news?

**Comment by BernardPuel** [comment]
v4.1.2 is targeted for Week30 (July).

**Comment by angelo-zehnder** [comment]
Ok, so basically the kirkstone branch will stay broken still for a few months then! Great news!

**Comment by sidalit** [comment]
@angelo-zehnder you can add something like this in your conf files as temporary workaround

```
# Prevents processing non-existent gcc append file
BBMASK += "/meta-st-stm32mp/recipes-devtools/gcc/"
```

**Comment by angelo-zehnder** [comment]
> @angelo-zehnder you can add something like this in your conf files as temporary workaround
> 
> ```
> # Prevents processing non-existent gcc append file
> BBMASK += "/meta-st-stm32mp/recipes-devtools/gcc/"
> ```

Sorry but I'm not going to do that.
Kirkstone is an LTS version and bugs must be fixed. I'm going to continue using my fixed branch.
This bug makes impossible to use this meta-layer cause to a blocking error, honestly I do not think this is the way to handle a bug like this.

**Comment by angeloc** [comment]
this PR is not going to be merged or the bug fixed, therefore closing it

**Comment by BernardPuel** [comment]
Hello Angelo, I understand your point but ST has chosen for the maintenance releases to upgrade the whole distribution and to privilege robustness and reliability of the whole system (with a drawback on reactivity).

This means a lot of effort in integration and validation (> 10000 system test ran and analyzed). And it impacts the release plan frequency.

This also means, customers need to live with some temporary patch in between. Thanks for your patience.

**Comment by angeloc** [comment]
> to privilege robustness and reliability of the whole system (with a drawback on reactivity).

I don't understand what's the robustness on having a broken meta-layer for the LTS version of yocto.

If you really don't want to fix this branch, open another one and call it kirkstone-4.0.15.

I think nobody cares if you want to keep things "stable" while staying on an old kirkstone version. I think people are more interested in updating their kirkstone sooner to have all the advantages of running an LTS.

My 2 cents ...

**Comment by BernardPuel** [comment]
Yes this is what is ongoing: move from current 4.0.11 to 4.0.15 and there is no issue with gcc 11.4.
But it will be only delivered in v4.1.2 later on.

**Comment by angeloc** [comment]
It's your policy, you do whatever you want, but anyway the argument doesn't stand.

4.0.15 was out in December, you shall have already fixed the bug considering you have a PR doing that.

4.1.2 is another release entirely and while you want to maintain the timing (not sure why) you're leaving your LTS users with a broken experience.

Hopefully, the OSS gives us third parties the freedom to fix!

**Comment by BernardPuel** [comment]
Yes I think we are completely in line with this statement.

**Pull request closed without merging**
