### PR TITLE
Set IMAGE_ROOTFS_EXTRA_SPACE were needed

### PR DESCRIPTION
**Pull request by jobol**
Setting IMAGE_ROOTFS_SIZE to the same value as
IMAGE_ROOTFS_MAXSIZE requires IMAGE_OVERHEAD_FACTOR
to be 1 (it was the case) and IMAGE_ROOTFS_EXTRA_SPACE
to be 0 (it was missing).

Signed-off-by: José Bollo <jose.bollo@iot.bzh>

### CODE REVIEW

**Comment by BernardPuel** [comment]
Thanks for your contribution, internal ticket to integration team was entered.
I will inform you about evolution soon.

**Comment by BernardPuel** [comment]
Looking at Yocto documentation: 
https://www.yoctoproject.org/docs/2.0/ref-manual/ref-manual.html#var-IMAGE_ROOTFS_EXTRA_SPACE

This variable is already set by default to 0. So what is the problem you encountered that needs to explicitly set it to 0 ?

**Comment by jobol** [comment]
I was trying to integrate your **meta-st-stm32mp** in AGL project as a BSP.
I hadn't checked the reason why the extra space is not zero but AGL uses systemd and I can see in poky:
```
poky/meta/recipes-core/images/core-image-minimal.bb:IMAGE_ROOTFS_EXTRA_SPACE_append = "${@bb.utils.contains("DISTRO_FEATURES", "systemd", " + 4096", "" ,d)}"
```
But it looks not like the main reason.
**meta-st-stm32mp** produces 4 partitions and I don't remember the partitions that were in trouble.

**Comment by BernardPuel** [comment]
Ok we understand now. It will be integrated in next release.

**Pull request closed without merging**
