### PR TITLE
systemd-conf: renamed bbappend to match upstream poky zeus

### PR DESCRIPTION
**Pull request by DasRoteSkelett**
Signed-off-by: Matthias Schoepfer <matthias.schoepfer@ithinx.io>

### CODE REVIEW

**Comment by bernardoaraujor** [comment]
I would appreciate this PR being merged, this is breaking my builds.

**Comment by DasRoteSkelett** [comment]
Maybe you need to pull in poky? 
Upstream has systemd-conf.243.2.bb. Check here:
http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-core/systemd?h=zeus

Changed here:
commit 61d60f43369fc337b2de8483cca0e9d48150313c
Author: Adrian Bunk <bunk@stusta.de>
Date:   Tue Dec 31 16:18:19 2019 +0200

    systemd: Upgrade 243 -> 243.2
    
    Bugfix-only changes on the 243 stable branch.
    
    (From OE-Core rev: fd1aa49d8a25767953e8b1beb91001d5e115f781)
    
    Signed-off-by: Adrian Bunk <bunk@stusta.de>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
    Signed-off-by: Armin Kuster <akuster808@gmail.com>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

**Comment by bernardoaraujor** [comment]
hey @DasRoteSkelett sorry the way I wrote my message was probably not very clear.
I'm agreeing with your PR and asking for it to be merged, as I will also benefit from it.

**Comment by DasRoteSkelett** [comment]
Hi @bernardoaraujor ,

ah, okay, I inserted a "but" before you half-sentence in my mind... :-)

**Comment by rzr** [comment]
This change is desirable when building openembedded core image (not poky)
I can explain how to reproduce.

   openembedded-core/meta/recipes-core/systemd/systemd-conf_243.2.bb

cc: @OpenSTLinux

**Comment by DasRoteSkelett** [comment]
Already merged by @cpriouzeau, closing this therefore

**Pull request closed without merging**
