### PR TITLE
layer: add mickledore compatibility

### PR DESCRIPTION
**Pull request by quaresmajose**
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

### CODE REVIEW

**Comment by quaresmajose** [comment]
Gently ping.

**Comment by BernardPuel** [comment]
Internal ticket is under analysis from integration team.

**Comment by BernardPuel** [comment]
Here is internal feedback: 
"We target to support a new branch as Mickledore only when a tag are available
on the branch."

So should arrive soon ...

**Comment by quaresmajose** [comment]
Hope it can be fixed soon to make possible to build this layer with oe-core master branch.
Thanks

**Comment by BernardPuel** [comment]
The tag is planned by Yocto on 28 th of April. So it is not soon but it is the way ST works: we don't want to expose non mature components to our customers.

**Comment by quaresmajose** [comment]
Yes, it's still a long time. I'm going to leave this PR open because I need this branch and you can close it if you think it is not adequate. 
I still need this branch in my fork to validate the on going development on OE-core master branch.

**Comment by kanavin** [comment]
What if the customers want to stay close to upstream yocto development (the benefits of that are well known)? This policy holds them hostage to older yocto, for the reason that they should not be deciding for themselves.

**Comment by BernardPuel** [comment]
After the tag is available on Yocto, ST will push the related branch in this layer for people willing to get some advanced delivery before the official OSTL complete ones (only on latest LTS).

See: https://github.com/STMicroelectronics/meta-st-stm32mp/branches/stale

ST considers that before this, it is community work.

**Comment by quaresmajose** [comment]
Integrated in https://github.com/STMicroelectronics/meta-st-stm32mp/commit/eb9bc83d4137c974daf0a7afc2e221f07728419d

**Pull request closed without merging**
