### PR TITLE
libdrm: make this bbappend version agnostic

### PR DESCRIPTION
**Pull request by quaresmajose**
This will make it compatibel with langdale and master

langdale: 2.4.113
master: 2.4.114

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

### CODE REVIEW

**Comment by quaresmajose** [comment]
maybe a better solution can be make it version agnostic `recipes-graphics/drm/libdrm_%.bbappend`

**Comment by quaresmajose** [comment]
Gently ping.

**Comment by BernardPuel** [comment]
Hello Jose, PR not accepted by Integration team. 
Even if it could solve the issue here, it can create issues in the futur (not refering to the right compatible version). I am checking for workaround with them.

**Comment by BernardPuel** [comment]
we pushed a langdale branch on this repo. Is it not ok for you ?

**Comment by quaresmajose** [comment]
> we pushed a langdale branch on this repo. Is it not ok for you ?

I am build this branch with oe-core master branch and version on oe-core is not the same as the one on langdale branch.
My intention with this PR is to make possible to build this branch with oe-core master but I can take care of this issue in my layer with a BBMASK.

**Pull request closed without merging**
