### PR TITLE
MACHINE: Move LOADADDR into include

### PR DESCRIPTION
**Pull request by ostaebler**
Move the setting of the default LOADADDR into an include instead of
setting this in each machine.

### CODE REVIEW

**Comment by ostaebler** [comment]
Any comments on this?

**Comment by BernardPuel** [comment]
Hello,
Thanks for your proposal. I have entered internal ticket for analysis and integration in our public delivery. After short discussion with integration team, it seems relevant for the time being to integrate it. I will inform you after confirmation and delivery date.

**Comment by BernardPuel** [comment]
Your patch will be integrated in next release (V1.1.0 planned end of Sept).

**Comment by BernardPuel** [comment]
Sorry my mistake, next release is V1.2.0. 
V1.1.0 slot is already over internally.

**Pull request closed without merging**
