### PR TITLE
libdrm_2.4.100.bbappend: moved to libdrm_2.4.101.bbappend

### PR DESCRIPTION
**Pull request by DasRoteSkelett**
This is needed from upstream version bump on poky, commit hash
009735549b78196d9ccd9abf84a7b6c918fd6f77

Signed-off-by: Matthias Schoepfer <matthias.schoepfer@ithinx.io>

### CODE REVIEW

**Comment by BernardPuel** [comment]
Thanks for your contribution, I have entered an internal ticket to integration team.

**Comment by BernardPuel** [comment]
We are currently based on a yocto-3.1.1 and in that version libdrm is the version 2.4.100. 
But if we update yocto to 3.1.2 then agree, libdrm moved to 2.4.101 and we can take it.

**Comment by BernardPuel** [comment]
Dunfell 3.1.2 is on going, the PR has been cherry-picked.

**Comment by koansoftware** [comment]
I propose to rename it to libdrm_2.4.%.bbappend

**Comment by BernardPuel** [comment]
The update will be delivered in V2.1.0 (mid nov).
% cannot be integrated as the patch might be not compatible with Dunfell version used by ST delivery. So version should be explicit.

**Comment by koansoftware** [comment]
> The update will be delivered in V2.1.0 (mid nov).
> % cannot be integrated as the patch might be not compatible with Dunfell version used by ST delivery. So version should be explicit.

No problem, I solved forking on my own repo

**Comment by BernardPuel** [comment]
PR integrated (First version).

**Pull request closed without merging**
