### PR TITLE
GCNANO-USERLAND: fix PACKAGECONFIG names to fill RPROVIDES libs

### PR DESCRIPTION
**Pull request by abuzarra**
Signed-off-by: Arturo Buzarra <arturo.buzarra@digi.com>

### CODE REVIEW

**Comment by BernardPuel** [comment]
Thanks for your contribution Arturo, I have entered internal ticket for processing.

**Comment by abuzarra** [comment]
any update about this PR?

**Comment by BernardPuel** [comment]
Your contribution will be integrated in the next minor release = v4.0.2 this week.

**Comment by BernardPuel** [comment]
Delivered in openstlinux-5.15-yocto-kirkstone-mp1-v22.07.27 tag and the followings ...

**Pull request closed without merging**
